package Test;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import pages.AddressPage;
import pages.AddressesPage;
import pages.LoginPage;
import pages.MainPage;
import pages.MyAccountPage;

public class FPTestCase7 {
WebDriver driver;
	
	@BeforeTest
	public void setBaseUrl() {
		System.setProperty("webdriver.chrome.driver","./src/main/resources/chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("http://automationpractice.com/index.php");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}
	
	@Test(
		groups = {"sanity", "regression"},
		description = "Login user with a correct username and password"
	)
	public void successfullyLogin() {
		MainPage mainPage = new MainPage(driver);
		LoginPage loginPage = new LoginPage(driver);
		mainPage.clicksignIn();
		loginPage.enterUserEmail("sergio12345@gmail.com");
		loginPage.enterUserPassword("00000");
		loginPage.clickSubmitButton();
	}
	
	@Test(
		dependsOnMethods = { "successfullyLogin" }, 
		groups = {"sanity", "regression"},
		description = "Add a new address"
	)
	public void AddNewAddress() {
		//Going to the My Addresses section
		MyAccountPage myAccountPage = new MyAccountPage(driver);
		myAccountPage.clickMyAddresses();
		
		//Hit the Add New Address button
		AddressesPage addressesPage = new AddressesPage(driver);
		addressesPage.clickAddNewAddressButton();
		
		//Writing all the necessary info for the new address
		AddressPage addressPage = new AddressPage(driver);
		addressPage.enterFirstName("Yael");
		addressPage.enterLastName("Santana");
		addressPage.enterCompany("Accenture");
		addressPage.enterAddress("Domicilio #1345");
		addressPage.enterAddressLine2("Interior #2");
		addressPage.enterCity("Ciudad");
		addressPage.selectState("Colorado");
		addressPage.enterPostalCode("45123");
		addressPage.selectCountry(0);
		addressPage.enterHomePhone("8549671230");
		addressPage.enterMobilePhone("4512478955");
		addressPage.enterAddressTitle("Autogenerated " + ((int) (Math.random() * 100)));
		
		//Hit the save button
		addressPage.clickSaveButton();
	}
	
	@AfterTest
	public void endSession() {
		driver.quit();
	}
}
